---
kind: pipeline
type: docker
name: push-latest
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: build-and-push
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/mu-semtech/semtech}/${DRONE_REPO_NAME}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  branch:
  - master
  event:
    exclude:
    - pull_request
---
kind: pipeline
type: docker
name: push-feature-build
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: push-feature-build
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/mu-semtech/semtech}/${DRONE_REPO_NAME}
    tags: ${DRONE_BRANCH/\//-}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - "*/*"
  event:
    exclude:
      - pull_request
---
kind: pipeline
type: docker
name: push-release
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: build-and-push-tag
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/mu-semtech/semtech}/${DRONE_REPO_NAME}
    tags: ${DRONE_TAG##v} # strips v from the tag
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
trigger:
  event:
  - tag
---
kind: pipeline
type: docker
name: dry-run
steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: dry-run
  image: plugins/docker
  settings:
    repo: ${DRONE_REPO_NAMESPACE/mu-semtech/semtech}/${DRONE_REPO_NAME}
    dry_run: true
trigger:
  event:
  - pull_request
---
kind: signature
hmac: 578d488d4f356d809f3179d2b831e80085f05cf1d04f26ccfab730b662b66878

...
